import { z } from 'zod'

export const quoteSchema = z.object({
  HST: z.number(),
  baseRate: z.number(),
  calculatedDistance: z.number(),
  createdAt: z.string(),
  destinationFormattedAddress: z.string(),
  destinationName: z.string(),
  destinationPlaceId: z.string(),
  distanceText: z.string(),
  distanceValue: z.number(),
  durationText: z.string(),
  durationValue: z.number(),
  endLat: z.number(),
  endLng: z.number(),
  firstName: z.string(),
  fuelSurcharge: z.number(),
  gratuity: z.number(),
  hoursLabel: z.string(),
  hoursValue: z.number(),
  id: z.string(),
  isItHourly: z.boolean(),
  isRoundTrip: z.boolean(),
  lastName: z.string(),
  originFormattedAddress: z.string(),
  originName: z.string(),
  originPlaceId: z.string(),
  passengersLabel: z.string(),
  passengersValue: z.number(),
  pickupDate: z.string(),
  pickupTime: z.string(),
  returnDate: z.string(),
  returnTime: z.string(),
  serviceTypeLabel: z.string(),
  serviceTypeValue: z.number(),
  startLat: z.number(),
  startLng: z.number(),
  totalFare: z.number(),
  updatedAt: z.string(),
  userEmail: z.string(),
  userId: z.null(),
  vehicleTypeLabel: z.string(),
  vehicleTypeValue: z.number(),
  quote_number: z.number(),
})

export type Quote = z.infer<typeof quoteSchema>
